name: Lint 

on:
  push:
    branches:
      - main

# env: 
#   NODE_VERSION: 18

jobs:
  linting:
    name: Linting 
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint
